---
language: go
go:
- '1.17.x'
- '1.16.x'
- master
matrix:
  allow_failures:
  - go: master
  fast_finish: true
install:
- make clean clean-goimports
- make dependencies dependencies-download
- make coverage-install
before_script:
- make coverage-before
- curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.43.0
- golangci-lint --version
script:
- make test
- make lint
after_script:
- make coverage-after
