---
env:
  global:
  - CC_TEST_REPORTER_ID=
language: go
go:
- '1.17.x'
- '1.16.x'
- '1.15.x'
- master
matrix:
  allow_failures:
  - rvm: ruby-head
  fast_finish: true
install:
- make lint-install
- make clean
- make clean-goimports
- make dependencies
- make dependencies-download
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
script:
- make test
- make lint
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
