---
env:
  global:
  - CC_TEST_REPORTER_ID=
language: go
go:
- '1.17.x'
- '1.16.x'
- master
matrix:
  allow_failures:
  - go: master
  fast_finish: true
install:
- make clean clean-goimports
- make dependencies dependencies-download
- make coverage-install
before_script:
- make lint-install
- make coverage-before
script:
- make test
- make lint
after_script:
- make coverage-after
