---
env:
  # This must be created during pipeline upload step to lock the build time
  DEPLOY_VERSION: $BUILD_TIME-$BUILDKITE_COMMIT-$BUILDKITE_BUILD_NUMBER-$BUILDKITE_BUILD_ID
steps:
- id: 'docker-build'
  label: ":docker: :package: for testing"
  agents:
    queue: enosi-build
  plugins:
  - ecr#v2.2.0:
      login: true
      no-include-email: true
      region: 'ap-southeast-2'
      retries: 5
  - docker-compose#v3.7.0:
      build:
      - app
      config:
      - docker-compose.ci.yml
      image-name:
      - test-$DEPLOY_VERSION
      image-repository: 178233295285.dkr.ecr.ap-southeast-2.amazonaws.com/go-base
- wait
- id: 'golint'
  label: ':golang::lint-roller: golint'
  agents:
    queue: enosi-build
  plugins:
    docker-compose:
      command: [".buildkite/lints/golint.sh"]
      config:
      - docker-compose.ci.yml
      run: app
- id: 'test'
  label: ':golang: testing'
  agents:
    queue: enosi-build
  plugins:
    docker-compose:
      command: ['.buildkite/tests/test.sh']
      config:
      - docker-compose.ci.yml
      run: app
- wait
- id: 'build'
  label: ':golang: building $BUILDKITE_BRANCH'
  agents:
    queue: enosi-build
  if: build.branch != 'main' && build.tag !~ /^(v\d+\.\d+\.\d+)(\-.+?)?$$/
  plugins:
    docker-compose:
      command: ['.buildkite/build/build.sh']
      config:
      - docker-compose.ci.yml
      run: app
- id: 'bundle'
  label: ':golang: build + zipping $BUILDKITE_BRANCH'
  agents:
    queue: enosi-build
  if: build.branch == 'main' || build.tag =~ /^(v\d+\.\d+\.\d+)(\-.+?)?$$/
  artifact_paths:
  - 'zip/**/*'
  plugins:
    docker-compose:
      command: ['.buildkite/bundle/bundle.sh']
      config:
      - docker-compose.ci.yml
      run: app
- wait
- id: 'release-latest'
  label: ':golang: copy this build of $BUILDKITE_BRANCH to "latest" release'
  agents:
    queue: enosi-build
  if: build.branch == 'main'
  plugins:
  - artifacts#v1.3.0:
      download: 'zip/**'
  command: '.buildkite/release/latest.sh'
- id: 'docker-release-latest'
  label: ":docker: :package: latest release for use"
  agents:
    queue: enosi-build
  branches:
  - main
  plugins:
  - ecr#v2.3.0:
      login: true
      no-include-email: true
      region: ap-southeast-2
  - docker-compose#v3.3.0:
      build:
      - app-production
      config:
      - docker-compose.production.yml
      push:
      - app-production:178233295285.dkr.ecr.ap-southeast-2.amazonaws.com/billing-adjustment:latest
      - app-production:178233295285.dkr.ecr.ap-southeast-2.amazonaws.com/billing-adjustment:latest-$BUILDKITE_BUILD_NUMBER
- id: 'docker-release-tagged'
  label: ":docker: :package: tagged release for use"
  agents:
    queue: enosi-build
  branches:
  - v*.*.*
  plugins:
  - ecr#v2.3.0:
      login: true
      no-include-email: true
      region: ap-southeast-2
  - docker-compose#v3.3.0:
      build:
      - app-production
      config:
      - docker-compose.production.yml
      push:
      - app-production:178233295285.dkr.ecr.ap-southeast-2.amazonaws.com/billing-adjustment:$BUILDKITE_TAG
      - app-production:178233295285.dkr.ecr.ap-southeast-2.amazonaws.com/billing-adjustment:$BUILDKITE_TAG-$BUILDKITE_BUILD_NUMBER
- wait
# Sandpit
- label: ':lambda: :rocket: direct deployment to sandpit'
  trigger: infra-enosi-sandpit
  async: false
  branches:
  - main
  build:
    message: ':partyparrot: triggering build on sandpit'
    commit: HEAD
    branch: production
    env:
      TF_VAR_billing_adjustment_artifact: '{"s3_bucket":"enosi-buildkite-artifacts","s3_key_prefix":"$BUILDKITE_PIPELINE_SLUG/latest/zip"}'
# Energy Locals (staging)
- label: ':lambda: :rocket: direct deployment to Energy Locals (staging)'
  trigger: infra-enosi-energy-locals
  async: false
  branches:
  - main
  build:
    message: ':partyparrot: triggering build on Energy Locals (staging)'
    commit: HEAD
    branch: staging
    env:
      TF_VAR_billing_adjustment_artifact: '{"s3_bucket":"enosi-buildkite-artifacts","s3_key_prefix":"$BUILDKITE_PIPELINE_SLUG/latest/zip"}'
# Simply Energy (staging)
- label: ':lambda: :rocket: direct deployment to Simply Energy (staging)'
  trigger: infra-enosi-simply-energy
  async: false
  branches:
  - main
  build:
    message: ':partyparrot: triggering build on Simply Energy (staging)'
    commit: HEAD
    branch: staging
    env:
      TF_VAR_billing_adjustment_artifact: '{"s3_bucket":"enosi-buildkite-artifacts","s3_key_prefix":"$BUILDKITE_PIPELINE_SLUG/latest/zip"}'
