---
on: [push, pull_request]
name: 'Test'
jobs:
  setup:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Install Go'
      uses: 'actions/setup-go@v2'
      with:
        go-version: '1.17.x'
    - name: 'Checkout code'
      uses: 'actions/checkout@v2'
    - uses: 'actions/cache@v2'
      with:
        # In order:
        # * Module download cache
        # * Build cache (Linux)
        # * Build cache (Mac)
        # * Build cache (Windows)
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          %LocalAppData%\go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
  test:
    needs: ['setup']
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Test'
      run: 'make test'
    - name: 'Publish code coverage'
      uses: 'paambaati/codeclimate-action@v3.0.0'
      env:
        CC_TEST_REPORTER_ID: <code_climate_reporter_id>
      with:
       coverageLocations: |
        ${{github.workspace}}/.coverage/coverage.out:gocov
